
lint:
  image: "python:3.9"
  variables:
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.cache/pre-commit
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    SKIP: docker-clang-format
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
      - ${PIP_CACHE_DIR}
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run -a


pytest:
  image: "gitlab-registry.cern.ch/lhcb-reco-dev/pv-finder:latest"

  only:
    - master
    - merge_request

  script:
    - pytest
